import type { AiReadinessTemplateDefinition } from "./types";

export const AI_READINESS_SYSTEM_TEMPLATE_VERSION = "1.0.0";

export const AI_READINESS_SYSTEM_TEMPLATE: AiReadinessTemplateDefinition = {
  pillars: [
    {
      id: "technology",
      title: "Technology",
      description:
        "Governance degli strumenti AI, accessi, sicurezza, costi e readiness tecnica.",
      weight: 1,
    },
    {
      id: "context",
      title: "Context",
      description:
        "Qualita, accessibilita e ownership della conoscenza aziendale usata dall'AI.",
      weight: 1,
    },
    {
      id: "workflow",
      title: "Workflow",
      description:
        "Maturita dei processi, handoff, decisioni, baseline ROI e ridisegno operativo.",
      weight: 1,
    },
    {
      id: "adoption",
      title: "Adoption",
      description:
        "AI literacy, utilizzo reale, fiducia, training needs e cultura di sperimentazione.",
      weight: 1,
    },
    {
      id: "use_cases",
      title: "Use Cases",
      description:
        "Capacita di identificare use case concreti, sicuri, pilotabili e collegati al business.",
      weight: 1,
    },
  ],
  sections: [
    {
      id: "technology-governance",
      pillarId: "technology",
      title: "Governance tecnica",
      description: "Quanto gli strumenti AI sono gestiti in modo centralizzato e sicuro.",
    },
    {
      id: "context-knowledge",
      pillarId: "context",
      title: "Conoscenza e dati",
      description: "Quanto il contesto aziendale e accessibile, versionato e governato.",
    },
    {
      id: "workflow-readiness",
      pillarId: "workflow",
      title: "Processi e redesign",
      description: "Quanto i workflow sono mappati e pronti per AI augmentation o automation.",
    },
    {
      id: "adoption-literacy",
      pillarId: "adoption",
      title: "Adozione e literacy",
      description: "Quanto le persone conoscono, usano e si fidano dell'AI.",
    },
    {
      id: "use-cases-quality",
      pillarId: "use_cases",
      title: "Qualita use case",
      description: "Quanto l'organizzazione sa proporre e validare use case AI.",
    },
  ],
  questions: [
    {
      id: "tech-approved-tools",
      pillarId: "technology",
      sectionId: "technology-governance",
      label: "Gli strumenti AI approvati sono definiti e comunicati chiaramente?",
      answerType: "scale",
      required: true,
      min: 0,
      max: 5,
      weight: 1,
    },
    {
      id: "tech-access-controls",
      pillarId: "technology",
      sectionId: "technology-governance",
      label: "SSO, MFA e controlli di accesso sono attivi sugli strumenti AI principali?",
      answerType: "scale",
      required: true,
      min: 0,
      max: 5,
      weight: 1,
    },
    {
      id: "tech-monitoring",
      pillarId: "technology",
      sectionId: "technology-governance",
      label: "L'azienda monitora costi, utilizzo, logging e incidenti legati all'AI?",
      answerType: "scale",
      required: true,
      min: 0,
      max: 5,
      weight: 1,
    },
    {
      id: "context-docs",
      pillarId: "context",
      sectionId: "context-knowledge",
      label: "Policy, procedure e documenti critici sono centralizzati e aggiornati?",
      answerType: "scale",
      required: true,
      min: 0,
      max: 5,
      weight: 1,
    },
    {
      id: "context-ownership",
      pillarId: "context",
      sectionId: "context-knowledge",
      label: "La conoscenza aziendale ha owner chiari e regole esplicite?",
      answerType: "scale",
      required: true,
      min: 0,
      max: 5,
      weight: 1,
    },
    {
      id: "context-systems",
      pillarId: "context",
      sectionId: "context-knowledge",
      label: "CRM, ERP, project data o knowledge base sono accessibili via API o integrazioni sicure?",
      answerType: "scale",
      required: true,
      min: 0,
      max: 5,
      weight: 1,
    },
    {
      id: "workflow-mapping",
      pillarId: "workflow",
      sectionId: "workflow-readiness",
      label: "I processi piu importanti sono mappati end-to-end con handoff e decision point?",
      answerType: "scale",
      required: true,
      min: 0,
      max: 5,
      weight: 1,
    },
    {
      id: "workflow-baselines",
      pillarId: "workflow",
      sectionId: "workflow-readiness",
      label: "Prima di introdurre AI vengono misurate baseline di tempo, qualita e costi?",
      answerType: "scale",
      required: true,
      min: 0,
      max: 5,
      weight: 1,
    },
    {
      id: "workflow-hitl",
      pillarId: "workflow",
      sectionId: "workflow-readiness",
      label: "I workflow AI prevedono chiaramente human-in-the-loop, escalation ed eccezioni?",
      answerType: "scale",
      required: true,
      min: 0,
      max: 5,
      weight: 1,
    },
    {
      id: "adoption-knowledge",
      pillarId: "adoption",
      sectionId: "adoption-literacy",
      label: "Quanto ti senti preparato su AI, Generative AI, limiti e rischi dati?",
      answerType: "scale",
      required: true,
      min: 0,
      max: 5,
      weight: 1,
    },
    {
      id: "adoption-frequency",
      pillarId: "adoption",
      sectionId: "adoption-literacy",
      label: "Con quale maturita usi strumenti AI nel lavoro quotidiano?",
      answerType: "scale",
      required: true,
      min: 0,
      max: 5,
      weight: 1,
    },
    {
      id: "adoption-sentiment",
      pillarId: "adoption",
      sectionId: "adoption-literacy",
      label: "Qual e il tuo atteggiamento prevalente verso l'AI in azienda?",
      answerType: "single_choice",
      required: true,
      weight: 1,
      options: [
        { value: "worried", label: "Preoccupato", score: 1 },
        { value: "skeptical", label: "Scettico", score: 2 },
        { value: "neutral", label: "Neutrale", score: 3 },
        { value: "curious", label: "Curioso", score: 4 },
        { value: "enthusiastic", label: "Entusiasta", score: 5 },
      ],
    },
    {
      id: "use-case-quality",
      pillarId: "use_cases",
      sectionId: "use-cases-quality",
      label: "L'organizzazione raccoglie e valuta use case AI con criteri chiari?",
      answerType: "scale",
      required: true,
      min: 0,
      max: 5,
      weight: 1,
    },
    {
      id: "use-case-risk",
      pillarId: "use_cases",
      sectionId: "use-cases-quality",
      label: "I use case vengono valutati per rischio, dati necessari e controllo umano prima del pilot?",
      answerType: "scale",
      required: true,
      min: 0,
      max: 5,
      weight: 1,
    },
    {
      id: "use-case-business",
      pillarId: "use_cases",
      sectionId: "use-cases-quality",
      label: "I use case sono collegati a obiettivi business, owner e metriche di successo?",
      answerType: "scale",
      required: true,
      min: 0,
      max: 5,
      weight: 1,
    },
    {
      id: "open-main-blocker",
      pillarId: "adoption",
      sectionId: "adoption-literacy",
      label: "Qual e oggi il principale blocco pratico all'adozione AI nella tua area?",
      answerType: "text",
      required: false,
    },
  ],
  scoringSchema: {
    version: "ai-readiness-core-1",
    scale: { min: 0, max: 5 },
    readinessFormula: {
      weightedAverageWeight: 0.65,
      weakestPillarWeight: 0.35,
    },
  },
};
